In [1]:
import numpy as np

In [2]:
print(type((1,2,3)))
print(type([1,2,3]))
print(type(np.array((1,2,3))))
print(type(np.array([1,2,3])))

<class 'tuple'>
<class 'list'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [11]:
np.zeros(5) #un solo numero para una dimension
np.zeros([5,5]) #un arreglo o tupla para varias diemnsiones
np.zeros((5,5))
np.zeros((1000, 200))

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [12]:
np.ones([7,2])

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [13]:
np.eye(5) #diagonal con unos y el resto zeros

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
np.arange(4,20) #El ultimo no lo toma en cuenta
np.arange(0,20,2) #del 0 al 20 en saltos de 2 (sin incluir al 20)
np.arange(10).reshape([2,5]) #solo se puede dividir en dimensiones si el numero de elementos es divisible para esas dimensiones

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [23]:
np.ones(12).reshape(4,3).shape # Muestra las dimensiones

(4, 3)

In [35]:
a = np.array([10,10,10])
b = np.array([5,5,5])

In [36]:
#Suma
a + b

array([15, 15, 15])

In [37]:
#Resta
a - b

array([5, 5, 5])

In [38]:
#Suma de un numero
a + 7

array([17, 17, 17])

In [39]:
#Multiplicacion
a * b

array([50, 50, 50])

In [41]:
#Division
a / b

array([2., 2., 2.])

In [42]:
a % b

array([0, 0, 0], dtype=int32)

In [43]:
muestra = np.arange(20).reshape(5,2,2)

In [44]:
muestra

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]]])

In [45]:
respuesta_glucosa = muestra > 5

In [46]:
respuesta_glucosa

array([[[False, False],
        [False, False]],

       [[False, False],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]]])

In [64]:
resp1 = muestra[respuesta_glucosa]
respuesta14 = resp1 < 14
resp2 = resp1[respuesta14]
respuesta_pares = resp2[::2]

In [65]:
respuesta_pares

array([ 6,  8, 10, 12])