In [3]:
import numpy as np

In [4]:
arreglo_grados = np.array([0,30,45,60,90])
arreglo_grados

array([ 0, 30, 45, 60, 90])

In [6]:
arreglo_radianes = arreglo_grados * np.pi / 180
arreglo_radianes

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [7]:
np.sin(arreglo_radianes)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [8]:
np.cos(arreglo_radianes)

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [9]:
np.tan(arreglo_radianes)

array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00,
       1.63312394e+16])

In [15]:
numero_random = np.random.randint(11) #Un numero entero random del 0 al 10
numero_random

9

In [19]:
numero_random_negativo = np.random.randint(-9,2)
numero_random_negativo

-3

In [21]:
arreglo_random = np.random.randint(10,20,8) #Un arreglo random de numeros entre el 10 y el 19, de 8 elementos
arreglo_random

array([12, 16, 14, 13, 15, 18, 12, 11])

In [23]:
np.random.rand(9) #Para numeros decimales, el numero de elementos se coloca como parametro
np.random.rand(3,2) #6 elementos 3x2 dimensiones

array([[0.60106675, 0.77047521],
       [0.32833286, 0.42552785],
       [0.13109396, 0.68655648]])

In [24]:
np.average(arreglo_random)

13.875

In [25]:
np.mean(arreglo_random)

13.875

In [26]:
np.median(arreglo_random)

13.5

In [27]:
np.std(arreglo_random)

2.2043990110685496

In [29]:
np.var(arreglo_random)

4.859375