In [1]:
import numpy as np

In [3]:
arreglo = np.arange(11) ** 2 #Elevar al cuadrado el arreglo
arreglo

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [4]:
arreglo[0:7]

array([ 0,  1,  4,  9, 16, 25, 36], dtype=int32)

In [5]:
arreglo[-6:-1]

array([25, 36, 49, 64, 81], dtype=int32)

In [6]:
arreglo[2:-3]

array([ 4,  9, 16, 25, 36, 49], dtype=int32)

In [7]:
arreglo[:]

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [8]:
arreglo[0:6:2] #arreglo del 0 al 6 saltando de 2 en  2 indices

array([ 0,  4, 16], dtype=int32)

In [10]:
arreglo[::2]

array([  0,   4,  16,  36,  64, 100], dtype=int32)