In [49]:
import numpy as np
import pandas as pd
from scipy import ndimage
from scipy import misc
# 1) Examen

## 2) Crear un vector de ceros de tamaño 10
v_ceros = np.zeros(10)
v_ceros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
## 3) Crear un vector de ceros de tamaño 10 y el de la posicion 5 sea igual a 1
v_ceros2 = np.zeros(10)
v_ceros2[4] = 1 #el indice es 4 porque se empieza a indexar en cero y requerimos cambiar la posicion 5
v_ceros2

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [7]:
## 4) Cambiar el orden de un vector de 50 elementos, el de la posicion 1 es el de la 50 etc.
vector = np.arange(50)

for i in range(25):
    aux = vector[i]
    vector[i] = vector[49 - i]
    vector[49 - i] = aux
    
vector

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [10]:
## 5) Crear una matriz de 3 x 3 con valores del cero al 8
matriz08 = np.arange(9).reshape(3,3)
matriz08

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [22]:
## 6) Encontrar los indices que no sean cero en un arreglo
arreglo = np.array([1,2,0,0,4,0])
arreglo = arreglo[(arreglo != 0)]
arreglo

array([1, 2, 4])

In [13]:
## 7) Crear una matriz de identidad 3 x 3 
matriz_identidad = np.identity(3)
matriz_identidad

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
## 8) Crear una matriz 3 x 3 x 3 con valores randomicos
matriz_random = np.random.random((3, 3))
matriz_random

array([[0.46916656, 0.35779872, 0.97587746],
       [0.29933853, 0.98524074, 0.30916446],
       [0.78457185, 0.48731932, 0.73686768]])

In [35]:
## 9) Crear una matriz 10 x 10 y encontrar el mayor y el menor
matriz10x10 = np.arange(100).reshape(10,10)
maximo_minimo = [matriz10x10.max(), matriz10x10.min()]
maximo_minimo

[99, 0]

In [52]:
## 10) Sacar los colores RGB unicos en una imagen (cuales rgb existen ej: 0, 0, 0 - 255,255,255 -> 2 colores)
mapache = misc.face()
colores_unicos = mapache[mapache == [5,5,5] and mapache == [100,100,100]]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [59]:
## 11) ¿Como crear una serie de una lista, diccionario o arreglo?
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))

serie_diccionario = pd.Series(
    mydict)

series_lista = pd.Series(
    mylist
    )

series_arreglo = pd.Series(
    myarr
    )

series_lista
series_arreglo
serie_diccionario

a     0
b     1
c     2
e     3
d     4
f     5
g     6
h     7
i     8
j     9
k    10
l    11
m    12
n    13
o    14
p    15
q    16
r    17
s    18
t    19
u    20
v    21
w    22
x    23
y    24
z    25
dtype: int64

In [73]:
## 12) ¿Como convertir el indice de una serie en una columna de un DataFrame?
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict) 
# Transformar la serie en dataframe y hacer una columna indice

df1 = pd.DataFrame(ser, columns = ['numero']) #al transformar la serie en dataframe automaticamente toma la primera columna como indice
df1

numero
a       0
b       1
c       2
e       3
d       4
f       5
g       6
h       7
i       8
j       9
k      10
l      11
m      12
n      13
o      14
p      15
q      16
r      17
s      18
t      19
u      20
v      21
w      22
x      23
y      24
z      25

In [78]:
## 13) ¿Como combinar varias series para hacer un DataFrame?
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))
df2 = pd.DataFrame(ser1,ser2)
df2

0
0   a
1   b
2   c
3   e
4   d
5   f
6   g
7   h
8   i
9   j
10  k
11  l
12  m
13  n
14  o
15  p
16  q
17  r
18  s
19  t
20  u
21  v
22  w
23  x
24  y
25  z

In [87]:
## 14) ¿Como obtener los items que esten en una serie A y no en una serie B?
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])
items = ser1 != ser2
items

0    True
1    True
2    True
3    True
4    True
dtype: bool

In [95]:
## 15) ¿Como obtener los items que no son comunes en una serie A y serie B?
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])
items_nocomunes = ser1[ser1 != ser2]
items_nocomunes

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [90]:
## 16) ¿Como obtener el numero de veces que se repite un valor en una serie?
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))
ser.value_counts()

h    7
b    6
c    6
a    4
g    4
f    2
e    1
dtype: int64

In [97]:
## 17) ¿Como mantener los 2 valores mas repetidos de una serie, y a los demas valores cambiarles por 0 ?
np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 5, [12]))
ser

0     2
1     3
2     3
3     2
4     4
5     3
6     3
7     4
8     1
9     1
10    3
11    1
dtype: int32

In [104]:
## 18) ¿Como transformar una serie de un arreglo de numpy a un DataFrame con un `shape` definido?
ser = pd.Series(np.random.randint(1, 10, 35))
array = np.array(ser).reshape(7,5)
df3 = pd.DataFrame(array)
df3

0  1  2  3  4
0  8  2  6  2  8
1  9  5  2  8  2
2  7  2  4  2  6
3  2  5  8  7  6
4  5  9  9  7  4
5  6  3  8  5  3
6  9  9  7  7  4

In [106]:
## 19) ¿Obtener los valores de una serie conociendo la posicion por indice?
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]
# a e i o u

ser[pos]

0     a
4     e
8     i
14    o
20    u
dtype: object

In [108]:
## 20) ¿Como anadir series vertical u horizontalmente a un DataFrame?
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))
df4 = pd.DataFrame(ser1, ser2)
df4

0
a NaN
b NaN
c NaN
d NaN
e NaN

In [118]:
## 21)¿Obtener la media de una serie agrupada por otra serie?
frutas = pd.Series(np.random.choice(['manzana', 'banana', 'zanahoria'], 10))
pesos = pd.Series(np.linspace(1, 10, 10))
print(pesos.tolist())
print(frutas.tolist())
#> [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
#> ['banana', 'carrot', 'apple', 'carrot', 'carrot', 'apple', 'banana', 'carrot', 'apple', 'carrot']

# Los valores van a cambiar por ser random
# apple     6.0
# banana    4.0
# carrot    5.8
# dtype: float64

print(frutas.median())

[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
['manzana', 'manzana', 'manzana', 'zanahoria', 'zanahoria', 'banana', 'manzana', 'banana', 'banana', 'zanahoria']


TypeError: could not convert string to float: 'manzana'

In [117]:
## 22)¿Como importar solo columnas especificas de un archivo csv?

path = "https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv"

columnas = ['crim','zn']

df1 = pd.read_csv(
    path,
    nrows=10,
    usecols = columnas)

df1

crim    zn
0  0.00632  18.0
1  0.02731   0.0
2  0.02729   0.0
3  0.03237   0.0
4  0.06905   0.0
5  0.02985   0.0
6  0.08829  12.5
7  0.14455  12.5
8  0.21124  12.5
9  0.17004  12.5